bug|tests(utils): defaultdict() > {}
in `utils.get_thresholds()` we build a dictionary of thresholds (now that we support multi-class thresholding).

This built a dictionary of thresholds using `defaultdict()` but for some reason under Python 3.10/3.11 the test of equality when calculating the thresholds for method `std` (`standard deviation`) as the `defaultdict()` was returned with the "default" being `None` (as [expected](https://docs.python.org/3/library/collections.html#collections.defaultdict)).

These tests didn't fail under GNU/Linux.

The logs show...

```
FAILED tests/test_filters_minicircle.py::test_get_threshold_stddev - AssertionError: assert defaultdict(N...8836019106)]}) == approx({'belo...58836019106]})

  (pytest_assertion plugin: representation of details failed: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/python_api.py:267: TypeError: unsupported operand type(s) for -: 'list' and 'list'.
   Probably an object has a faulty __repr__.)
```

- As we don't actually need any of the special properties/tricks that `defaultdict()` confers (primarily returning an empty object of specified type which defaults to `None`) we switch to using plain dictionaries.
- We also replace the `assert` to use `io.dict_almost_equal()` to check whether the dictionaries are equal or not.