feature(classes): Add class attributes and dunder methods
- adds `thresholds` and `threshold_method` properties to `GrainCrop` class
- adds `config` and `full_mask_tensor` properties to `TopoStats` class
- updates tests in light of these changes
- correct minor tpyo in `default_config.yaml`

The main things that this adds though is `__getstate__`/`__setstate__` methods for each of the classes. The reason for
doing so is because classes that have `@property` objects associated with them can't be pickled and so they need
explicit conversion to dictionaries.

See...

- [here](https://stackoverflow.com/a/1939384/1444043)
- [Handling stateful objects](https://docs.python.org/3/library/pickle.html#pickle-state)

Unfortunately this still fails...

```
from pathlib import Path
import pickle as pkl
from topostats.classes import TopoStats

OUTDIR = Path.cwd()
OUTFILE = OUTDIR / "empty.topostats"
empty_topostats = TopoStats(img_path = None)
with OUTFILE.open(mode="wb") as f:
    pkl.dump(empty_topostats, f)
TypeError                                 Traceback (most recent call last)
Cell In[905], line 2
      1 with OUTFILE.open(mode="wb") as f:
----> 2     pkl.dump(empty_topostats, f)

TypeError: cannot pickle 'property' object

empty_topostats.__getstate__()
{'_image_grain_crops': <property at 0x7fb40c81e0c0>,
 '_filename': <property at 0x7fb40c81d170>,
 '_pixel_to_nm_scaling': <property at 0x7fb40c81f880>,
 '_img_path': PosixPath('/home/neil/work/git/hub/AFM-SPM/TopoStats/tmp'),
 '_image': <property at 0x7fb39ce731a0>,
 '_image_original': <property at 0x7fb39ce71e40>,
 '_full_mask_tensor': <property at 0x7fb39ce72980>,
 '_topostats_version': <property at 0x7fb39ce71d00>,
 '_config': <property at 0x7fb39ce72020>}
```

Everything is _still_ a `property`.

This dummy example works fine though...

```
@dataclass
class dummy():
    var1: int | None = None
    var2: float | None = None
    var3: str | None = None
    var4: list[int] | None = None
    var5: dict[str, str] | None = None

    def __getstate__(self):
        # return {"_var1": self._var1,
        #         "_var2": self._var2,
        #         "_var3": self._var3,
        #         "_var4": self._var4,
        #         "_var5": self._var5,}
        state = self.__dict__.copy()
        return state

    def __setstate__(self, state):
        # self._var1 = state["_var1"]
        # self._var2 = state["_var2"]
        # self._var3 = state["_var3"]
        # self._var4 = state["_var4"]
        # self._var5 = state["_var5"]
        self.__dict__.update(state)

    @property
    def var1(self) -> int:
        """
        Getter for the ``var1`` attribute.

        Returns
        -------
        int
            Returns the value of ``var1``.
        """
        return self._var1

    @var1.setter
    def var1(self, value: int) -> None:
        """
        Setter for the ``var1`` attribute.

        Parameters
        ----------
        value : int
            Value to set for ``var1``.
        """
        self._var1 = value

    @property
    def var2(self) -> float:
        """
        Getter for the ``var2`` attribute.

        Returns
        -------
        float
            Returns the value of ``var2``.
        """
        return self._var2

    @var2.setter
    def var2(self, value: float) -> None:
        """
        Setter for the ``var2`` attribute.

        Parameters
        ----------
        value : float
            Value to set for ``var2``.
        """
        self._var2 = value

    @property
    def var3(self) -> str:
        """
        Getter for the ``var3`` attribute.

        Returns
        -------
        str
            Returns the value of ``var3``.
        """
        return self._var3

    @var3.setter
    def var3(self, value: str) -> None:
        """
        Setter for the ``var3`` attribute.

        Parameters
        ----------
        value : str
            Value to set for ``var3``.
        """
        self._var3 = value

    @property
    def var4(self) -> list[int]:
        """
        Getter for the ``var4`` attribute.

        Returns
        -------
        list[int]
            Returns the value of ``var4``.
        """
        return self._var4

    @var4.setter
    def var4(self, value: list[int]) -> None:
        """
        Setter for the ``var4`` attribute.

        Parameters
        ----------
        value : list[int]
            Value to set for ``var4``.
        """
        self._var4 = value

    @property
    def var5(self) -> dict[str,str]:
        """
        Getter for the ``var5`` attribute.

        Returns
        -------
        dict[str,str]
            Returns the value of ``var5``.
        """
        return self._var5

    @var5.setter
    def var5(self, value: dict[str,str]) -> None:
        """
        Setter for the ``var5`` attribute.

        Parameters
        ----------
        value : dict[str,str]
            Value to set for ``var5``.
        """
        self._var5 = value

OUTFILE = OUTDIR / "empty.dummy"
empty_dummy = dummy()
with OUTFILE.open(mode="wb") as f:
    pkl.dump(empty_dummy, f)
```

...no error and I don't understand where I/we have gone wrong?!?!?!?!

I'm somewhat inclined to move away from `@dataclass` and using `@property` to provide the `setter` / `getter` design
pattern and instead use plain classes with attributes.