dependency(matplotlib): Pins matplotlib~=3.9.4
In addressing #986 I tested in a fresh virtual environment. This pulled in
[matplotlib-3.10.0](https://github.com/matplotlib/matplotlib/releases/tag/v3.10.0) which was released 2024-12-14 (two
days ago!). Our dependency on [topoly](topoly.cent.uw.edu.pl/documentation.html) doesn't work with this new version
because of the removal of `inset_location.InsetPosition` in favour of `inset_axes`.

This has been reported to the Topoly developers, see [ImportError: cannot import name 'InsetPosition' from
'mpl_toolkits.axes_grid1.inset_locator' · Issue #5 ·
ilbsm/topoly_tutorial](https://github.com/ilbsm/topoly_tutorial/issues/5) and hopefully won't take long to resolve. For
now though we pin our dependency `matplotlib~=3.9.4` and all tests pass.